#!/usr/bin/env python3
"""Compose asu_v2/official_submission/agent.py FROM the proven sources so the
embedded snippets cannot drift (Codex P1-2/P1-3): the v2 pass helpers are
embedded from asu_v2/agent/v2_repairs.py, the runner scaffolding from the v1
official agent, and the header is rewritten to describe the ACTUAL v2 stack.

Usage:  python3 compose_official_agent.py [--check-against <runs_dir>]
--check-against verifies the composed repair() output is byte-identical to
<runs_dir>/<Block>/<stack>/cand.py for all 5 blocks (exit nonzero otherwise).
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

V2 = Path(__file__).resolve().parent.parent
ROOT = V2.parent
sys.path.insert(0, str(ROOT / "asu_work" / "agent"))
sys.path.insert(0, str(V2 / "agent"))
import v2_repairs  # noqa: E402

STACK_NAME = "via-bar-safe+track-shift+v1-patch"
BLOCKS = ["Block1", "Block2", "Block3", "Block6", "Block7"]

V2_HEADER = '''#!/usr/bin/env python3
"""ASU block-repair agent — OFFICIAL SUBMISSION entry point (v2, 2026-07-26).

Contest runner contract (official_eval/run_official_eval.py):
    python3 agent.py <info_json> --model <model_name>
The agent container runs from `python:3.10-slim` (only `google-genai` + `shapely`
on top), `--read-only`, with NO KLayout binary on PATH. The organizer's evaluator
renders and scores the emitted script AFTERWARD, on the host, in KLayout 0.30.1.

WHAT THIS AGENT EMITS (v2 stack, deterministic, zero model calls):
  stripped(original) + via-bar-safe + track-shift + v1-patch
  * via-bar-safe: replaces each flagged multi-cut via array with one continuous
    bar ONLY where the bar touches exactly the same electrical components as
    the original cuts on BOTH adjacent metal layers, compared per side
    (full-stack union-find; landings that would short or open keep their
    original cuts — fail closed).
  * track-shift: translates off-grid M4/M5/M6 tracks back to the routing
    grid/pitch, co-translating riding V3/V4 cuts and patching M3 end-caps;
    every move is accepted only if, LAYER-AWARE: the same-layer touch set, every
    stationary adjacent-via positive-area contact set, and every riding cut's
    opposite-side host set are unchanged, and patches touch only their host
    rail and no foreign via; M6 tracks interacting V6 are refused. There is
    no flat-projection acceptance path.
  * v1-patch: minimal V1.M1.EN.1 enclosure restoration where provably safe.
  All checks run inside the organizer's KLayout render; on a block with no
  matching flagged geometry every pass is a no-op and the original renders
  unchanged (eligible floor; its FVR is the evaluator's fresh-DRC ratio).

This file is GENERATED by asu_v2/tools/compose_official_agent.py from
asu_v2/agent/v2_repairs.py — do not edit by hand.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

_WRITE_RE = re.compile(r"layout\\.write\\(\\s*(['\\"]).*?\\1\\s*\\)")


def _strip_write(script: str) -> str:
    return _WRITE_RE.sub("", script)


def _looks_like_pya_layout(script: str) -> bool:
    """Fail-closed guard: only transform scripts that build a `layout` with pya."""
    return "layout" in script and ("pya" in script or "klayout" in script)


def _log(msg: str):
    print(f"[asu-official] {msg}", file=sys.stderr, flush=True)

'''

BODY = '''

def repair(original: str) -> tuple[str, str]:
    """Return (emitted_script, note). Deterministic; no KLayout at runtime."""
    if not _looks_like_pya_layout(original):
        return original, "not a pya layout script — emitted original (eligible floor)"
    emitted = (_strip_write(original) + "\\n" + via_bar_safe_snippet()
               + "\\n" + track_shift_snippet() + "\\n" + v1_patch_snippet())
    return emitted, "via-bar-safe + track-shift + v1-patch repair applied"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="ASU block-repair agent (official, v2)")
    ap.add_argument("info_json")
    # The runner always passes --model <name>; this deterministic agent ignores it.
    ap.add_argument("--model", default="none")
    a = ap.parse_args(argv)

    info = json.loads(Path(a.info_json).read_text(encoding="utf-8"))
    case = info.get("case_name", "?")
    layout_path = Path(info["path_to_layout_script"])
    output_path = Path(info["output_path"])
    original = layout_path.read_text(encoding="utf-8", errors="replace")

    emitted, note = repair(original)
    _log(f"{case}: {note}")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(emitted, encoding="utf-8")
    _log(f"{case}: wrote {output_path} ({len(emitted):,} chars)")

    # Usage is recorded by the benchmark model-service wrapper, not the agent, and
    # the official runner mounts the agent read-only. Best-effort only; never crash.
    usage_path = info.get("usage_path")
    if usage_path:
        try:
            up = Path(usage_path)
            up.parent.mkdir(parents=True, exist_ok=True)
            up.write_text(json.dumps({"input_tokens": 0, "output_tokens": 0,
                                      "calls": 0}, indent=1))
        except OSError as e:
            _log(f"usage write skipped (read-only, expected under official runner): "
                 f"{type(e).__name__}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''


def snippet_defs() -> str:
    parts = []
    for helper_name, builder_name, gen in (
            ("_VIA_BAR_SAFE_HELPER", "via_bar_safe_snippet",
             v2_repairs.via_bar_safe_pass),
            ("_TRACK_SHIFT_HELPER", "track_shift_snippet",
             v2_repairs.track_shift_pass),
            ("_V1_PATCH_HELPER", "v1_patch_snippet", v2_repairs.v1_patch_pass)):
        helper = getattr(v2_repairs, helper_name)
        body = gen()
        # everything the generator appends after the helper, as a literal
        tail = body[len(helper):]
        parts.append(f"{helper_name} = {helper!r}\n\n"
                     f"_{builder_name.upper()}_TAIL = {tail!r}\n\n"
                     f"def {builder_name}() -> str:\n"
                     f'    """Byte-identical to v2_repairs.{gen.__name__}()."""\n'
                     f"    return {helper_name} + _{builder_name.upper()}_TAIL\n")
    return "\n".join(parts)


def compose() -> str:
    return V2_HEADER + snippet_defs() + BODY


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check-against", default=None,
                    help="runs dir with <Block>/<stack>/cand.py to byte-verify")
    a = ap.parse_args()
    text = compose()
    out = V2 / "official_submission" / "agent.py"
    out.write_text(text, encoding="utf-8")
    print(f"wrote {out} ({len(text):,} chars)")

    # self-check: builders in the composed file == the dev generators
    ns = {}
    exec(compile(text.replace('if __name__ == "__main__":\n    sys.exit(main())',
                              ''), "agent_v2", "exec"), ns)
    assert ns["via_bar_safe_snippet"]() == v2_repairs.via_bar_safe_pass()
    assert ns["track_shift_snippet"]() == v2_repairs.track_shift_pass()
    assert ns["v1_patch_snippet"]() == v2_repairs.v1_patch_pass()
    print("builder equality: OK")

    if a.check_against:
        runs = Path(a.check_against)
        tc = (ROOT / "ICLAD-Hackathon-2026" / "problem-categories"
              / "ICLAD26-ASU-Problems" / "testcase" / "asap7" / "block"
              / "layout_script")
        ok = True
        for blk in BLOCKS:
            emitted, _ = ns["repair"]((tc / f"{blk}.py").read_text())
            cand = (runs / blk / STACK_NAME / "cand.py").read_text()
            match = emitted == cand
            ok &= match
            print(f"{blk}: byte-identical to measured candidate: {match}")
        if not ok:
            print("MISMATCH — do not ship")
            return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
