#!/usr/bin/env python3
"""KAT (known-answer-test) engine — cocotb-style golden TB, zero deps.

Python owns stimulus and checking; the simulator runs a dumb generic
REPLAY TB that executes a vector program and dumps a response trace:

  vector program (text, one command per line; '#' comments)
      Z <n>              assert por_n low n cycles, release, settle 5
      W <addr> <data> <prot>   AHB write (hex hex hex)
      R <addr> <prot>          AHB read  -> trace line
      N <n>              idle n cycles
      S                  sample SoC outputs -> trace line

  response trace (written by the TB)
      R <seq> <addr> <rdata> <resp> <cycle>
      S <seq> <gpio_out> <gpio_oe> <uart_tx> <uart_rts_n> <pwm0> <pwm1> \
              <cpu_irq> <cpu_irq_id> <wdt_rst_req> <cycle>

Expected files use the same trace format, so they can come from EITHER
source: --record replays the program on the REFERENCE RTL (golden-record —
valid whenever a trusted implementation exists), or ref_models.py predicts
them from the inferred YAML (hidden-testcase path). Comparison ignores the
trailing cycle column (value correctness here; timing divergence is the
STG differential's job) and scores fractionally with first-fail decode.

The replay TB template is easy-tier (secure_periph_soc ports); the
medium/hard generalization is to render the DUT hookup from the skeleton's
port contract (validators.skeleton_contract already parses it).

  python3 kat_engine.py --gen-smoke          # write kat/easy_smoke.vec
  python3 kat_engine.py --record             # reference RTL -> .expected
  python3 kat_engine.py --check [--rtl DIR]  # candidate vs .expected
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
NXP = HERE.parent
KAT_DIR = HERE / "kat"
DEF_REF = NXP / "rtl"
DEF_GEN = NXP / "agent_out/rtl"
DEF_WORK = NXP / "agent_out/tmp/kat"

S_FIELDS = ["gpio_out", "gpio_oe", "uart_tx", "uart_rts_n", "pwm0", "pwm1",
            "cpu_irq", "cpu_irq_id", "wdt_rst_req"]

TB = r"""// tb_replay.v — generated by kat_engine.py; generic vector-replay engine.
`timescale 1ns/1ps
module tb_replay;
    reg         clk, por_n;
    reg  [31:0] cpu_haddr;  reg [1:0] cpu_htrans; reg cpu_hwrite;
    reg  [2:0]  cpu_hsize, cpu_hburst, cpu_hprot;
    reg  [31:0] cpu_hwdata;
    wire [31:0] cpu_hrdata; wire cpu_hready; wire [1:0] cpu_hresp;
    reg  [31:0] gpio_in;    wire [31:0] gpio_out, gpio_oe;
    wire        uart_tx;    reg uart_rx, uart_cts_n; wire uart_rts_n;
    wire        pwm0, pwm1, cpu_irq; wire [2:0] cpu_irq_id; wire wdt_rst_req;

    integer vfd, rfd, code, n, seq, waitc; integer cycle;
    reg [8*256-1:0] vecf, resf;
    reg [8*8-1:0] cmd;
    reg [31:0] a_, d_, p_, rd; reg [1:0] rs;

    secure_periph_soc dut (
        .clk(clk), .por_n(por_n),
        .cpu_haddr(cpu_haddr), .cpu_htrans(cpu_htrans), .cpu_hwrite(cpu_hwrite),
        .cpu_hsize(cpu_hsize), .cpu_hburst(cpu_hburst), .cpu_hprot(cpu_hprot),
        .cpu_hwdata(cpu_hwdata), .cpu_hrdata(cpu_hrdata), .cpu_hready(cpu_hready),
        .cpu_hresp(cpu_hresp),
        .gpio_in(gpio_in), .gpio_out(gpio_out), .gpio_oe(gpio_oe),
        .uart_tx(uart_tx), .uart_rx(uart_rx), .uart_cts_n(uart_cts_n),
        .uart_rts_n(uart_rts_n),
        .pwm0(pwm0), .pwm1(pwm1), .cpu_irq(cpu_irq), .cpu_irq_id(cpu_irq_id),
        .wdt_rst_req(wdt_rst_req)
    );

    initial clk = 0;
    always #5 clk = ~clk;
    always @(posedge clk) cycle <= cycle + 1;

    task ahb_write(input [31:0] addr, input [31:0] data, input [2:0] prot);
        begin
            @(negedge clk);
            cpu_haddr=addr; cpu_htrans=2'b10; cpu_hwrite=1'b1; cpu_hprot=prot;
            cpu_hsize=3'b010; cpu_hburst=3'b000;
            @(posedge clk);
            @(negedge clk);
            cpu_htrans=2'b00; cpu_hwrite=1'b0; cpu_hwdata=data;
            @(posedge clk);
            waitc = 0;
            while (!cpu_hready && waitc < 64) begin
                @(posedge clk); waitc = waitc + 1; end
        end
    endtask

    task ahb_read(input [31:0] addr, input [2:0] prot,
                  output [31:0] rdata, output [1:0] resp);
        begin
            @(negedge clk);
            cpu_haddr=addr; cpu_htrans=2'b10; cpu_hwrite=1'b0; cpu_hprot=prot;
            cpu_hsize=3'b010; cpu_hburst=3'b000;
            @(posedge clk);
            @(negedge clk);
            cpu_htrans=2'b00;
            @(posedge clk);
            waitc = 0;
            while (!cpu_hready && waitc < 64) begin
                @(posedge clk); waitc = waitc + 1; end
            rdata = cpu_hrdata; resp = cpu_hresp;
        end
    endtask

    initial begin : main
        if (!$value$plusargs("vec=%s", vecf)) vecf = "kat.vec";
        if (!$value$plusargs("res=%s", resf)) resf = "kat.res";
        vfd = $fopen(vecf, "r"); rfd = $fopen(resf, "w");
        if (vfd == 0) begin $display("KAT: cannot open vectors"); $finish; end
        cycle = 0; seq = 0;
        por_n=1'b0; cpu_haddr=0; cpu_htrans=0; cpu_hwrite=0; cpu_hsize=0;
        cpu_hburst=0; cpu_hprot=0; cpu_hwdata=0; gpio_in=0;
        uart_rx=1'b1; uart_cts_n=1'b0;
        while (!$feof(vfd)) begin
            code = $fscanf(vfd, "%s", cmd);
            if (code == 1) begin
                case (cmd)
                    "Z": begin
                        code = $fscanf(vfd, "%d", n);
                        por_n = 1'b0; repeat (n) @(posedge clk);
                        por_n = 1'b1; repeat (5) @(posedge clk);
                        $fwrite(rfd, "Z %0d %0d\n", seq, cycle);
                    end
                    "W": begin
                        code = $fscanf(vfd, "%h %h %h", a_, d_, p_);
                        ahb_write(a_, d_, p_[2:0]);
                        $fwrite(rfd, "W %0d %h %0d\n", seq, a_, cycle);
                    end
                    "R": begin
                        code = $fscanf(vfd, "%h %h", a_, p_);
                        ahb_read(a_, p_[2:0], rd, rs);
                        $fwrite(rfd, "R %0d %h %h %h %0d\n",
                                seq, a_, rd, rs, cycle);
                    end
                    "N": begin
                        code = $fscanf(vfd, "%d", n);
                        repeat (n) @(posedge clk);
                    end
                    "S": begin
                        @(negedge clk);
                        $fwrite(rfd, "S %0d %h %h %b %b %b %b %b %h %b %0d\n",
                                seq, gpio_out, gpio_oe, uart_tx, uart_rts_n,
                                pwm0, pwm1, cpu_irq, cpu_irq_id, wdt_rst_req,
                                cycle);
                    end
                endcase
                seq = seq + 1;
            end
        end
        $fwrite(rfd, "DONE %0d\n", seq);
        $fclose(vfd); $fclose(rfd);
        $finish;
    end
    initial begin #10_000_000; $display("KAT_TIMEOUT"); $finish; end
endmodule
"""


# ── smoke suite (reset values + rw + system behaviors, easy tier) ─────────────
UART, GPIO, TIMER, WDT, IRQA, UNMAP = (0x0000, 0x1000, 0x2000, 0x3000,
                                       0x4000, 0x5000)
PRIV, USER = 1, 0
WDT_KEY, WDT_KICK = 0xABCD1234, 0xFEEDC0DE


def gen_smoke() -> str:
    """easy_smoke v2 — register-map-exact (from rtl_gen_lib source):
    reset values, w/r-back, timer count/freeze/pwm, uart fifo fill (12 deep —
    splits FIFO_DEPTH 8 vs 16), full irq path (uart+gpio+soft through the
    aggregator w/ priority id), wdt unlock/window-kick/kick-no-reload
    (asserts ACTUAL library behavior incl. the last-NBA bug)/freeze,
    privilege, unmapped, in-block unknown offset, re-reset."""
    # NOTE: no comments in the emitted file — the replay TB's $fscanf reads
    # bare tokens and would count comment words as (unknown) commands,
    # desyncing seq numbering between TB and ref_models
    W = lambda a, d, p=PRIV: f"W {a:08x} {d:08x} {p}"
    R = lambda a, p=PRIV: f"R {a:08x} {p}"
    v = ["Z 5", "S"]
    # reset-value sweep (documented per rtl_gen_lib register maps)
    v += [R(UART+o) for o in (0x00, 0x04, 0x08, 0x0C, 0x10, 0x14)]
    v += [R(GPIO+o) for o in (0x00, 0x04, 0x08, 0x14, 0x18, 0x1C, 0x20)]
    v += [R(TIMER+o) for o in (0x00, 0x04, 0x08, 0x0C, 0x10, 0x20, 0x24)]
    v += [R(WDT+o) for o in (0x00, 0x04, 0x08, 0x0C, 0x10, 0x1C)]
    v += [R(IRQA+o) for o in (0x00, 0x04, 0x08, 0x0C, 0x10, 0x1C)]
    # gpio: out/dir w/r-back + outputs sample
    v += [W(GPIO+0x04, 0xA5A5A5A5), R(GPIO+0x04),
          W(GPIO+0x08, 0x0000FFFF), R(GPIO+0x08), "S"]
    # timer ch0: load, enable (v0<=ld0), count, ctrl readback, freeze, pwm
    v += [W(TIMER+0x00, 0x000000FF), W(TIMER+0x08, 0x00000001),
          "N 16", R(TIMER+0x04), "N 16", R(TIMER+0x04), R(TIMER+0x08),
          W(TIMER+0x08, 0x00000000), R(TIMER+0x04), R(TIMER+0x04),
          W(TIMER+0x0C, 0x00000010), W(TIMER+0x08, 0x00000009), "S"]
    # uart: tx_en=0 + div=13, fill 12 chars (depth-16 not full / depth-8 full),
    # status, then irq_en -> istat -> irq to aggregator (id=1) -> clear chain
    v += [W(UART+0x0C, 0x00000D00), R(UART+0x0C)]
    v += [W(UART+0x00, 0x40 + i) for i in range(1, 13)]
    v += [R(UART+0x08), W(UART+0x10, 0x000000FF), R(UART+0x10),
          R(UART+0x14), "S",
          W(UART+0x10, 0x00000000), R(UART+0x14),
          R(IRQA+0x04), W(IRQA+0x14, 0x00000002), R(IRQA+0x04), "S"]
    # gpio irq: level-active (ien=3, iedge=0, ipol=0 -> lv=~gs=all-ones),
    # W1C re-latch subtlety, disable, clear, aggregator cleanup
    v += [W(GPIO+0x14, 0x00000003), R(GPIO+0x20), "S",
          W(GPIO+0x20, 0x00000003), R(GPIO+0x20),
          W(GPIO+0x14, 0x00000000), W(GPIO+0x20, 0x00000003), R(GPIO+0x20),
          W(IRQA+0x14, 0x00000004), R(IRQA+0x04), "S"]
    # irqa soft irq: pend[4], priority id, clear
    v += [W(IRQA+0x1C, 0x00000010), R(IRQA+0x04), "S",
          W(IRQA+0x1C, 0x00000000), W(IRQA+0x14, 0x00000010),
          R(IRQA+0x04), "S"]
    # wdt: unlock -> enable(win) -> early kick (window violation, iqw, no
    # reload) -> re-ctrl wen=0 -> kick (library bug: reload lost, countdown
    # continues) -> disable -> frozen
    v += [R(WDT+0x08),
          W(WDT+0x14, WDT_KEY), W(WDT+0x0C, 0x0000000F),
          "N 8", R(WDT+0x08),
          W(WDT+0x18, WDT_KICK), R(WDT+0x1C), R(WDT+0x08),
          W(WDT+0x1C, 0x00000002), R(WDT+0x1C),
          W(WDT+0x14, WDT_KEY), W(WDT+0x0C, 0x0000000D),
          W(WDT+0x18, WDT_KICK), R(WDT+0x08),
          W(WDT+0x14, WDT_KEY), W(WDT+0x0C, 0x0000000C),
          R(WDT+0x08), R(WDT+0x08), R(WDT+0x0C)]
    # system: unmapped, user-mode wdt (priv filter), unknown in-block offset
    v += [R(UNMAP), R(WDT+0x08, USER), W(WDT+0x0C, 0x00000003, USER),
          R(WDT+0x0C), R(UART+0x3C)]
    # re-reset: state wiped
    v += ["Z 5", R(GPIO+0x04), R(TIMER+0x08), R(WDT+0x08), R(UART+0x08), "S"]
    return "\n".join(v) + "\n"


# ── runner / comparator ───────────────────────────────────────────────────────
def run_vectors(rtl_dir: Path, vec: Path, work: Path, tag: str) -> tuple[Path | None, str]:
    work.mkdir(parents=True, exist_ok=True)
    (work / "tb_replay.v").write_text(TB)
    vfiles = sorted(str(p) for p in Path(rtl_dir).glob("*.v"))
    if not vfiles:
        return None, f"no .v files in {rtl_dir}"
    sim = work / f"sim_{tag}"
    c = subprocess.run(["iverilog", "-g2005", "-o", str(sim), *vfiles,
                        str(work / "tb_replay.v")], capture_output=True, text=True)
    if c.returncode != 0:
        return None, "compile: " + c.stderr[-600:]
    res = work / f"{tag}.res"
    r = subprocess.run(["vvp", sim.name, f"+vec={vec.resolve()}",
                        f"+res={res.name}"],
                       cwd=work, capture_output=True, text=True, timeout=600)
    if "KAT_TIMEOUT" in r.stdout:
        return None, "TB timeout (SoC hung)"
    if r.returncode != 0:
        return None, "sim: " + (r.stderr[-400:] or r.stdout[-400:])
    return res, ""


def _parse_lines(lines: list[str]) -> list[list[str]]:
    """[[kind, seq, payload-fields...]] — R/S only (W/Z are timing anchors
    for ref_models, not checked values), trailing cycle dropped."""
    out = []
    for ln in lines:
        t = ln.split()
        if t and t[0] in ("R", "S"):
            out.append(t[:-1])
        elif t and t[0] == "DONE":
            out.append(t)
    return out


def compare_lines(got_lines: list[str], exp_lines: list[str]) -> dict:
    got, exp = _parse_lines(got_lines), _parse_lines(exp_lines)
    total = sum(1 for e in exp if e[0] in ("R", "S"))
    fails, first = 0, None
    for g, e in zip(got, exp):
        if g == e:
            continue
        fails += 1
        if first is None:
            if e[0] == "R":
                first = (f"seq {e[1]}: read @{e[2]}: got data={g[3]} "
                         f"resp={g[4]}, expected data={e[3]} resp={e[4]}")
            elif e[0] == "S":
                diffs = [f"{n}: got {a} exp {b}" for n, a, b
                         in zip(S_FIELDS, g[2:], e[2:]) if a != b]
                first = f"seq {e[1]}: outputs: " + "; ".join(diffs)
            else:
                first = f"trace tail mismatch: got {g} expected {e}"
    if len(got) != len(exp):
        fails += abs(len(got) - len(exp))
        first = first or (f"trace length: got {len(got)} lines, "
                          f"expected {len(exp)} (early termination?)")
    passed = max(total - fails, 0)
    return dict(ok=(fails == 0), passed=passed, total=total,
                score=(passed / total if total else 0.0), first_fail=first)


def compare(got_trace: Path, exp_trace: Path) -> dict:
    return compare_lines(got_trace.read_text().splitlines(),
                         exp_trace.read_text().splitlines())


def _load_calibration() -> dict | None:
    import json
    p = KAT_DIR / "calibration.json"
    return json.loads(p.read_text()) if p.is_file() else None


def run_kat(rtl_dir=DEF_GEN, vec=None, expected=None, work=DEF_WORK,
            model_predict=False, params=None) -> dict:
    """Agent-facing: replay `vec` on rtl_dir; compare against the recorded
    `expected` file, or (model_predict=True, the hidden-testcase path)
    against ref_models predictions anchored on the candidate's own trace."""
    vec = Path(vec or KAT_DIR / "easy_smoke.vec")
    if not vec.is_file():
        return dict(ok=False, passed=0, total=0, score=0.0,
                    first_fail=f"missing KAT vectors ({vec})", error="assets")
    got, err = run_vectors(Path(rtl_dir), vec, Path(work), "cand")
    if err:
        return dict(ok=False, passed=0, total=0, score=0.0,
                    first_fail=err, error=err)
    got_lines = got.read_text().splitlines()
    if model_predict:
        import ref_models
        consts = _load_calibration() or {}
        try:
            exp_lines = ref_models.predict(
                vec.read_text(), "\n".join(got_lines), params,
                K=consts.get("K", 3), RZ=consts.get("RZ", 2),
                DS=consts.get("DS", 2))
        except ref_models.CalibrationError as e:
            return dict(ok=False, passed=0, total=0, score=0.0,
                        first_fail=f"model desync: {e}", error=str(e))
        return compare_lines(got_lines, exp_lines)
    expected = Path(expected or KAT_DIR / "easy_smoke.expected")
    if not expected.is_file():
        return dict(ok=False, passed=0, total=0, score=0.0,
                    first_fail=f"missing KAT expected ({expected})",
                    error="assets")
    return compare_lines(got_lines, expected.read_text().splitlines())


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--gen-smoke", action="store_true")
    ap.add_argument("--record", action="store_true",
                    help="replay on reference RTL -> .expected")
    ap.add_argument("--check", action="store_true",
                    help="replay on candidate RTL, compare vs .expected")
    ap.add_argument("--model-check", action="store_true",
                    help="replay on candidate RTL, compare vs ref_models "
                         "prediction (hidden-testcase path)")
    ap.add_argument("--calibrate", action="store_true",
                    help="grid-search ref_models timing constants against "
                         "the golden .expected; store kat/calibration.json")
    ap.add_argument("--rtl", default=str(DEF_GEN))
    ap.add_argument("--ref", default=str(DEF_REF))
    ap.add_argument("--vec", default=str(KAT_DIR / "easy_smoke.vec"))
    ap.add_argument("--expected", default=str(KAT_DIR / "easy_smoke.expected"))
    a = ap.parse_args()
    KAT_DIR.mkdir(exist_ok=True)

    if a.gen_smoke:
        Path(a.vec).write_text(gen_smoke())
        n = sum(1 for l in Path(a.vec).read_text().splitlines()
                if l and not l.startswith("#"))
        print(f"wrote {a.vec} ({n} commands)")
    if a.record:
        res, err = run_vectors(Path(a.ref), Path(a.vec), DEF_WORK, "ref")
        if err:
            print(f"KAT record ERROR: {err}"); return 2
        Path(a.expected).write_text(res.read_text())
        print(f"recorded {a.expected} "
              f"({sum(1 for _ in open(a.expected))} trace lines)")
    if a.calibrate:
        import json
        import ref_models
        consts, miss = ref_models.calibrate(Path(a.vec).read_text(),
                                            Path(a.expected).read_text())
        (KAT_DIR / "calibration.json").write_text(
            json.dumps(dict(K=consts[0], RZ=consts[1], DS=consts[2],
                            mismatches=miss)))
        print(f"calibrated K={consts[0]} RZ={consts[1]} DS={consts[2]} "
              f"({miss} residual mismatches)")
        if miss:
            return 3
    if a.check:
        r = run_kat(Path(a.rtl), a.vec, a.expected)
        print(f"KAT {'PASS' if r['ok'] else 'FAIL'}: {r['passed']}/{r['total']}"
              + (f" | first fail: {r['first_fail']}" if r["first_fail"] else ""))
        return 0 if r["ok"] else 1
    if a.model_check:
        r = run_kat(Path(a.rtl), a.vec, model_predict=True)
        print(f"KAT-MODEL {'PASS' if r['ok'] else 'FAIL'}: "
              f"{r['passed']}/{r['total']}"
              + (f" | first fail: {r['first_fail']}" if r["first_fail"] else ""))
        return 0 if r["ok"] else 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
