#!/usr/bin/env python3
"""Dual-SoC random-stimulus differential gate (EvolVE STG, LLM-free).

ONE trace-writing TB with a deterministic LCG stimulus stream (AHB reads/
writes over all peripheral bases + unmapped, WDT key injection, gpio_in/
uart_rx/cts side-band churn) is compiled and run TWICE — once against the
reference RTL, once against the agent-generated RTL — and the two output
traces are diffed offline. Separate compiles sidestep the module-name
collision (both sets define secure_periph_soc et al.).

What it catches that tb_selfcheck.v tolerates: parameter divergence
(FIFO depths, dividers, debounce), address-map swaps, and any behavioral
drift visible on the SoC's output pins under randomized traffic.

Only meaningful when a reference implementation of the SAME SoC exists
(easy tier); for hidden testcases there is no golden RTL to diff against.

Standalone:  python3 stg_diff.py [--ref DIR] [--gen DIR] [--ntxn N] [--seed S]
From agent:  stg_diff.run_diff(ref_dir, gen_dir) -> dict
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
NXP = HERE.parent
DEF_REF = NXP / "rtl"
DEF_GEN = NXP / "agent_out/rtl"
DEF_WORK = NXP / "agent_out/tmp/stg"

# columns of one trace line, after the leading cycle count
FIELDS = ["gpio_out", "gpio_oe", "uart_tx", "uart_rts_n", "pwm0", "pwm1",
          "cpu_irq", "cpu_irq_id", "wdt_rst_req", "cpu_hready", "cpu_hresp",
          "cpu_hrdata"]

TB = r"""// tb_trace.v — generated by stg_diff.py; deterministic LCG stimulus,
// per-cycle output trace. Same binary semantics both runs; only the RTL set
// under test changes.
`timescale 1ns/1ps
module tb_trace;
    reg         clk, por_n;
    reg  [31:0] cpu_haddr;  reg [1:0] cpu_htrans; reg cpu_hwrite;
    reg  [2:0]  cpu_hsize, cpu_hburst, cpu_hprot;
    reg  [31:0] cpu_hwdata;
    wire [31:0] cpu_hrdata; wire cpu_hready; wire [1:0] cpu_hresp;
    reg  [31:0] gpio_in;    wire [31:0] gpio_out, gpio_oe;
    wire        uart_tx;    reg uart_rx, uart_cts_n; wire uart_rts_n;
    wire        pwm0, pwm1, cpu_irq; wire [2:0] cpu_irq_id; wire wdt_rst_req;

    integer fd; integer cycle; reg tracing;
    reg [8*256-1:0] tracef;
    reg [31:0] rnd, ntxn;
    reg [31:0] rd; reg [1:0] rs;

    secure_periph_soc dut (
        .clk(clk), .por_n(por_n),
        .cpu_haddr(cpu_haddr), .cpu_htrans(cpu_htrans), .cpu_hwrite(cpu_hwrite),
        .cpu_hsize(cpu_hsize), .cpu_hburst(cpu_hburst), .cpu_hprot(cpu_hprot),
        .cpu_hwdata(cpu_hwdata), .cpu_hrdata(cpu_hrdata), .cpu_hready(cpu_hready),
        .cpu_hresp(cpu_hresp),
        .gpio_in(gpio_in), .gpio_out(gpio_out), .gpio_oe(gpio_oe),
        .uart_tx(uart_tx), .uart_rx(uart_rx), .uart_cts_n(uart_cts_n),
        .uart_rts_n(uart_rts_n),
        .pwm0(pwm0), .pwm1(pwm1), .cpu_irq(cpu_irq), .cpu_irq_id(cpu_irq_id),
        .wdt_rst_req(wdt_rst_req)
    );

    initial clk = 0;
    always #5 clk = ~clk;

    function [31:0] lcg(input [31:0] x);
        lcg = x * 32'd1664525 + 32'd1013904223;
    endfunction

    // AHB-Lite master tasks (same phasing as tb_selfcheck.v)
    task ahb_write(input [31:0] addr, input [31:0] data, input [2:0] prot);
        begin
            @(negedge clk);
            cpu_haddr=addr; cpu_htrans=2'b10; cpu_hwrite=1'b1; cpu_hprot=prot;
            cpu_hsize=3'b010; cpu_hburst=3'b000;
            @(posedge clk);
            @(negedge clk);
            cpu_htrans=2'b00; cpu_hwrite=1'b0; cpu_hwdata=data;
            @(posedge clk);
            while (!cpu_hready) @(posedge clk);
        end
    endtask

    task ahb_read(input [31:0] addr, input [2:0] prot,
                  output [31:0] rdata, output [1:0] resp);
        begin
            @(negedge clk);
            cpu_haddr=addr; cpu_htrans=2'b10; cpu_hwrite=1'b0; cpu_hprot=prot;
            cpu_hsize=3'b010; cpu_hburst=3'b000;
            @(posedge clk);
            @(negedge clk);
            cpu_htrans=2'b00;
            @(posedge clk);
            while (!cpu_hready) @(posedge clk);
            rdata = cpu_hrdata; resp = cpu_hresp;
        end
    endtask

    // per-cycle output trace
    always @(posedge clk) begin
        cycle <= cycle + 1;
        if (tracing)
            $fwrite(fd, "%0d %h %h %b %b %b %b %b %h %b %b %h %h\n",
                    cycle, gpio_out, gpio_oe, uart_tx, uart_rts_n, pwm0, pwm1,
                    cpu_irq, cpu_irq_id, wdt_rst_req, cpu_hready, cpu_hresp,
                    cpu_hrdata);
    end

    integer i, j;
    reg [31:0] base, addr, data, pick; reg [2:0] prot, sel;
    initial begin : main
        if (!$value$plusargs("trace=%s", tracef)) tracef = "trace.txt";
        if (!$value$plusargs("ntxn=%d",  ntxn))   ntxn   = 400;
        if (!$value$plusargs("seed=%d",  rnd))    rnd    = 32'hC0FFEE01;
        fd = $fopen(tracef, "w");
        cycle = 0; tracing = 0;
        por_n=0; cpu_haddr=0; cpu_htrans=0; cpu_hwrite=0; cpu_hsize=0;
        cpu_hburst=0; cpu_hprot=0; cpu_hwdata=0; gpio_in=0;
        uart_rx=1; uart_cts_n=0;
        repeat (5) @(posedge clk);
        por_n = 1;
        repeat (5) @(posedge clk);
        tracing = 1;
        for (i = 0; i < ntxn; i = i + 1) begin
            rnd = lcg(rnd); pick = rnd;
            rnd = lcg(rnd); gpio_in = rnd;
            rnd = lcg(rnd); uart_rx = (rnd[3:0] != 4'h0);  // mostly idle-high
            uart_cts_n = rnd[8];
            // burst txns are index-scheduled (every 32nd), round-robin over
            // ALL bases — LCG low bits correlate across draws, so gating
            // bursts AND base choice on one draw starves whole peripherals
            if (i[4:0] == 5'd0) sel = i[7:5];
            else                sel = pick[18:16];
            case (sel)                           // 6/8 mapped, WDT double-weight
                3'd0: base = 32'h0000_0000;      // UART
                3'd1: base = 32'h0000_1000;      // GPIO
                3'd2: base = 32'h0000_2000;      // TIMER
                3'd3: base = 32'h0000_3000;      // WDT
                3'd4: base = 32'h0000_4000;      // IRQA
                3'd5: base = 32'h0000_3000;      // WDT (privilege paths)
                3'd6: base = 32'h0000_1000;      // GPIO
                default: base = 32'h0000_5000;   // unmapped -> fabric timeout
            endcase
            rnd = lcg(rnd); addr = base | {24'b0, rnd[5:2], 2'b00};
            rnd = lcg(rnd); data = rnd;
            if (pick[31:28] == 4'h1) data = 32'hABCD_1234;   // WDT unlock key
            if (pick[31:28] == 4'h2) data = 32'hFEED_C0DE;   // WDT kick key
            prot = {2'b00, pick[27]};
            if (i[4:0] == 5'd0) begin
                // burst: 12 back-to-back writes to the block's data register
                // (offset 0), then a sweep of its low registers — fills a
                // shallow FIFO but not a deep one, so depth/full-flag
                // divergence lands in the status-read trace immediately
                // (sparse random traffic never queues >1 entry)
                for (j = 0; j < 12; j = j + 1) begin
                    rnd = lcg(rnd);
                    ahb_write(base, rnd, prot);
                end
                for (j = 0; j < 8; j = j + 1)
                    ahb_read(base | {24'b0, j[3:0], 2'b00}, prot, rd, rs);
            end
            else if (pick[3]) ahb_write(addr, data, prot);
            else              ahb_read(addr, prot, rd, rs);
        end
        repeat (300) @(posedge clk);   // drain: timer/uart/wdt tails
        tracing = 0;
        $fclose(fd);
        $finish;
    end
    initial begin
        #4_000_000;
        $display("TB_TIMEOUT"); $fclose(fd); $finish;
    end
endmodule
"""


def _compile_and_run(rtl_dir: Path, tag: str, work: Path,
                     ntxn: int, seed: int) -> tuple[Path | None, str]:
    vfiles = sorted(str(p) for p in Path(rtl_dir).glob("*.v"))
    if not vfiles:
        return None, f"{tag}: no .v files in {rtl_dir}"
    sim = work / f"sim_{tag}"
    c = subprocess.run(["iverilog", "-g2005", "-o", str(sim), *vfiles,
                        str(work / "tb_trace.v")],
                       capture_output=True, text=True)
    if c.returncode != 0:
        return None, f"{tag} compile: {c.stderr[-600:]}"
    trace = f"trace_{tag}.txt"
    r = subprocess.run(["vvp", sim.name, f"+trace={trace}",
                        f"+ntxn={ntxn}", f"+seed={seed}"],
                       cwd=work, capture_output=True, text=True, timeout=600)
    if "TB_TIMEOUT" in r.stdout:
        return None, f"{tag}: TB timeout (SoC hung — hready stuck low?)"
    if r.returncode != 0:
        return None, f"{tag} sim: {r.stderr[-400:] or r.stdout[-400:]}"
    return work / trace, ""


def _decode_mismatch(ref_line: str, gen_line: str) -> str:
    rt, gt = ref_line.split(), gen_line.split()
    cyc = rt[0]
    diffs = [f"{name}: ref={r} gen={g}"
             for name, r, g in zip(FIELDS, rt[1:], gt[1:]) if r != g]
    return f"cycle {cyc}: " + "; ".join(diffs)


def run_diff(ref_dir=DEF_REF, gen_dir=DEF_GEN, ntxn=400,
             seed=0xC0FFEE01, work=DEF_WORK) -> dict:
    """Returns dict(ok, lines, mismatches, first, error)."""
    work = Path(work)
    work.mkdir(parents=True, exist_ok=True)
    (work / "tb_trace.v").write_text(TB)
    ref_trace, err = _compile_and_run(ref_dir, "ref", work, ntxn, seed)
    if err:
        return dict(ok=False, lines=0, mismatches=0, first=None, error=err)
    gen_trace, err = _compile_and_run(gen_dir, "gen", work, ntxn, seed)
    if err:
        return dict(ok=False, lines=0, mismatches=0, first=None, error=err)

    ref_lines = ref_trace.read_text().splitlines()
    gen_lines = gen_trace.read_text().splitlines()
    n = min(len(ref_lines), len(gen_lines))
    bad = [i for i in range(n) if ref_lines[i] != gen_lines[i]]
    first = _decode_mismatch(ref_lines[bad[0]], gen_lines[bad[0]]) if bad else None
    mismatches = len(bad) + abs(len(ref_lines) - len(gen_lines))
    if len(ref_lines) != len(gen_lines) and not first:
        first = (f"trace length: ref={len(ref_lines)} gen={len(gen_lines)} "
                 f"(diverged simulation lifetime)")
    return dict(ok=(mismatches == 0), lines=n, mismatches=mismatches,
                first=first, error="")


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--ref", default=str(DEF_REF))
    ap.add_argument("--gen", default=str(DEF_GEN))
    ap.add_argument("--ntxn", type=int, default=400)
    ap.add_argument("--seed", type=lambda s: int(s, 0), default=0xC0FFEE01)
    ap.add_argument("--work", default=str(DEF_WORK))
    a = ap.parse_args()
    r = run_diff(Path(a.ref), Path(a.gen), a.ntxn, a.seed, Path(a.work))
    if r["error"]:
        print(f"STG-DIFF ERROR: {r['error']}")
        return 2
    print(f"STG-DIFF {'MATCH' if r['ok'] else 'MISMATCH'}: "
          f"{r['lines']} traced cycles, {r['mismatches']} differing"
          + (f"\n  first divergence -> {r['first']}" if r["first"] else ""))
    return 0 if r["ok"] else 1


if __name__ == "__main__":
    sys.exit(main())
